"""Add car_images table and relationship

Revision ID: 363a9bc078f5
Revises: 9e42197ee1bd
Create Date: 2025-08-13 00:45:06.587416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363a9bc078f5'
down_revision = '9e42197ee1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_images')
    # ### end Alembic commands ###
